import Head from 'next/head';
import { useState } from 'react';
import { getData } from '../../src/helpers/HttpHandler';
import { BlogDetails, SingleBlogBanner } from '../../src/components';
import Layout from '../../src/components/layout';
import Modal from '../../src/components/modal';

export const getStaticPaths = async () => {

    return {
        paths: [], //indicates that no page needs be created at build time
        fallback: 'blocking' //indicates the type of fallback
    }
}

export async function getStaticProps(ctx) {
    const { bid } = ctx.params

    // const blog = await getData(`/blog/${bid}`)
    console.log(bid)
    // console.log(blog);

    return {
        props: {
            // blog
        }
    }
}



export default function Blog() {
    const [show, setShow] = useState(false);

    return (
        <>
            <Head>
                <title>Blog - Quality Homes Reimagined, LLC</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.png" />
            </Head>
            <Layout>
                <Modal show={show} setShow={setShow} />
                <SingleBlogBanner />
                <BlogDetails show={show} setShow={setShow} />
            </Layout>
        </>
    );
}
