import Head from 'next/head';
import { AllBlog, BlogBanner } from '../src/components';
import Layout from '../src/components/layout';
import { getData } from '../src/helpers/HttpHandler';

export default function Blog({ blogs }) {
  return (
    <>
      <Head>
        <title>Blog - Quality Homes Reimagined, LLC</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <Layout>
        <BlogBanner />
        <AllBlog
          blogs={blogs}
        />
      </Layout>
    </>
  );
}

export async function getStaticProps() {

  const blogs = await getData('/api/blogs')

  return {
    props: {
      blogs: blogs || null
    }
  }
}